POST http://localhost:8080/api/login
Content-Type: application/json

{"username":"test", "password":"1234"}

###
GET http://localhost:8080/api/test
Content-Type: application/json
Authorization: Bearer 3
