POST http://localhost:8080/api/login
Content-Type: application/json

{"username":"test", "password":"1234"}

###
GET http://localhost:8080/api/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTYxNzkxMTMzMX0.cLP1wWpAxXSSVH2FzRm5WA-hWoi4UMdeLu5-CUJyKP8
